baseURL = "https://nepal.allyouneedtoknow.tips/"
theme = "hugo-sustain"
defaultContentLanguage = "en"
languageCode = "en-US"
title = "Nepal all you need to know"
# Enable comments by entering your Disqus shortname
disqusShortname = "nepal-allyouneedtoknow"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-156024128-1"

[languages.en]
  weight = 0
  languageName = "English"
  contentDir = "content/en"

[languages.it]
  weight = 10
  languageName = "Italian"
  contentDir = "content/it"

[permalinks] 
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Alessandro Travi, Denise Caggio"
  description = "Nepal all you need to know"

  # Custom assets can be linked with their paths relative to static/
  custom_css = [ "css/main.css" ]
  custom_js  = [ "js/main.js" ]
  metadata_allowed_blog = [ "in-depth", "approfondimenti" ]
  theme_color = "#CB2E40"

[params.author1]
  name = "Alessandro"
  Website = "https://altr.dev"
  Twitter = "https://twitter.com/altrdev"
  Instagram = "https://www.instagram.com/alessandro.travi/"

[params.author2]
  name = "Denise"
  Website = "https://denisecaggio.wordpress.com/"
  Twitter = ""
  Instagram = "https://www.instagram.com/nonblonde.d/"

[params.social]
  Twitter       = "allyouneedtok"
  Instagram     = "allyouneedtoknow.tips"
  Facebook      = "All-you-need-to-know-107668107442136"

## Main Menu English
[[languages.en.menu.main]]
  name = "tips"
  weight = 100
  url = "/tips/"
[[languages.en.menu.main]]
  name = "in-depth"
  weight = 200
  url = "/in-depth/"
[[languages.en.menu.main]]
  name = "donate"
  weight = 300
  url = "/donate/"

## Main Menu Italian
[[languages.it.menu.main]]
  name = "consigli"
  weight = 100
  url = "/consigli/"
[[languages.it.menu.main]]
  name = "approfondimenti"
  weight = 200
  url = "/approfondimenti/"
[[languages.it.menu.main]]
  name = "donazioni"
  weight = 300
  url = "/donazioni/"
